name: Secret Scan

on:
  workflow_call

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check token
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "Token Missing"
            exit 1
          else
            echo "Token Available"
    fi
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        
